spring:
  datasource:
    url: jdbc:h2:file:./data/chore-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kids:
  contacts:
    ONE:
      name: Sam
      email: ""
      phone-number: ""
      ntfy-topic: ""
    TWO:
      name: Riley
      email: ""
      phone-number: ""
      ntfy-topic: ""

ntfy:
  base-url: ${NTFY_BASE_URL:https://ntfy.sh}
  access-token: ${NTFY_ACCESS_TOKEN:}

chore:
  notifications:
    interval-ms: 900000
