spring:
  datasource:
    url: jdbc:h2:file:./data/chore-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kids:
  contacts:
    ONE:
      name: Sam
      email: ""
      phone-number: ""
    TWO:
      name: Riley
      email: ""
      phone-number: ""

sms:
  enabled: ${SMS_ENABLED:false}
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  from-number: ${TWILIO_FROM_NUMBER:}

chore:
  notifications:
    interval-ms: 900000
